name: Our First Workflow

on:
  push:                
  workflow_dispatch:   

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, Github Actions'

  pwd-ls:
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - name: Change Directory and List files
        run: |
          cd ~
          ls -al
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1,3'  # 월/수 05:30(UTC)
    - cron: '30 5 * * 2,4'  # 화/목 05:30(UTC)

jobs:
  # (위의 echo, pwd-ls 그대로 두고)
  test_schedule:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: ${{ github.event.schedule != '30 5 * * 1,3' }}
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
