# .github/workflows/python.yml
name: Python run nbn
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip

      - name: Debug list files (optional)
        run: |
          pwd
          find . -maxdepth 2 -type f | sort

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run nbn.py (Multiplication Table)
        run: python nbn.py
